stages:
  preprocess_train:
    cmd: python .\src\preprocess_data.py

  preprocess_test:
    cmd: python .\src\preprocess_data.py -i data/raw/1_2024-05-13-00-25-22.csv
      data/raw/2_2024-05-13-00-12-15.csv data/raw/3_2024-05-13-00-29-59.csv

  train_model:
    cmd: python src\train_model.py
  test_model:
    cmd: python src\test_model.py
